trigger:
  - master

pool:
  vmImage: 'windows-latest' # set to windows-latest or another Windows vmImage for Windows builds

variables:
  dockerRegistryServiceConnection: powerbipoc.azurecr.io
  kubernetesServiceConnection: https://power-bi-poc-aks-cluster1-dns-ac40c9c1.hcp.westeurope.azmk8s.io:443
  imageName: pbirs

steps:
- script: |
    echo $(Build.SourceVersion)
    set currentBuildSourceVersion=$(Build.SourceVersion)
    set imageTag=%currentBuildSourceVersion:~0,7%
    echo %imageTag%
    echo ##vso[task.setvariable variable=imageTag]%imageTag%
  displayName: Set image tag

- task: Docker@2
  displayName: Build and Push image to Azure Container Registry
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: ./Dockerfile
    tags: |
      $(imageTag)
      latest
    containerRegistry: $(dockerRegistryServiceConnection)

- task: HelmDeploy@0
  displayName: Helm deploy
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: $(kubernetesServiceConnection)
    namespace: default
    command: upgrade
    releaseName: power-bi-report
    waitForExecution: false
    install: true
    arguments: --set image.tag=$(imageTag)
    chartType: FilePath
    chartPath: charts/pbirs
