apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pbirs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pbirs.labels" . | nindent 4 }}
type: Opaque
data:
  pbirs_user: {{ .Values.environments.pbirs_user | b64enc }}
  pbirs_password: {{ .Values.environments.pbirs_password | b64enc }}
  sa_password: {{ .Values.environments.sa_password | b64enc }}
